(()=>{const PDF='https://dld.utah.gov/wp-content/uploads/Driver-Handbook-REV-3.2026.pdf';const MAP={
 'Permit & licensing':{section:'Sections 2, 3, 4 & 6 · Licensing, permits, and examinations',page:13,summary:'Utah permits, driver education, licensing eligibility, and knowledge-test requirements.'},
 'Vehicle safety':{section:'Section 7 · Preparing your vehicle',page:26,summary:'Seat position, mirrors, belts, car seats, air bags, and vehicle safety checks.'},
 'Driving fundamentals':{section:'Section 8 · Basic driving',page:29,summary:'Backing, lane changes, parking, passing, signaling, steering, stopping, and turns.'},
 'Rules of the road':{section:'Section 9 · Rules of the road',page:39,summary:'Freeways, intersections, markings, speed, roundabouts, and traffic controls.'},
 'Signs & signals':{section:'Section 9 · Traffic controls, signals, and signs',page:45,summary:'Signal meanings, regulatory signs, warning signs, lane controls, and pavement markings.'},
 'School & rail':{section:'Section 14 · Sharing the road',page:87,summary:'School-bus stopping rules, school safety, trains, and railroad crossings.'},
 'Sharing the road':{section:'Section 14 · Sharing the road',page:74,summary:'Bicycles, pedestrians, motorcycles, trucks, emergency vehicles, and rail safety.'},
 'Impairment & safety':{section:'Sections 10 & 11 · Alcohol, drugs, distractions, and driving challenges',page:50,summary:'Alcohol and drug laws, distraction, fatigue, and safe decision-making.'},
 'Emergencies & conditions':{section:'Sections 11 & 12 · Driving challenges and emergencies',page:55,summary:'Weather, mountain and night driving, skids, hydroplaning, blowouts, brake failure, and crash avoidance.'},
 'Crashes & responsibility':{section:'Section 12 · Crashes and insurance',page:64,summary:'Defensive driving, crash responsibilities, financial responsibility, and insurance.'}};
const esc=s=>String(s).replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));let prior=null;
function question(){let h=document.querySelector('.question h1');return h&&window.REVIEWED_QUESTIONS.find(q=>q.question===h.textContent)}function add(){let q=question();if(!q||document.querySelector('[data-handbook]'))return;let target=document.querySelector('.question .feedback')||document.querySelector('.question .options');target.insertAdjacentHTML('beforebegin',`<button class="handbook-link" data-handbook="${esc(q.id)}" aria-haspopup="dialog">↗ Handbook section</button>`)}
function open(id){let q=window.REVIEWED_QUESTIONS.find(x=>x.id===id);if(!q)return;let m=MAP[q.category]||MAP['Rules of the road'];prior=document.activeElement;let el=document.createElement('div');el.className='handbook-modal';el.id='handbookModal';el.innerHTML=`<div class="handbook-backdrop" data-close></div><section class="handbook-dialog" role="dialog" aria-modal="true" aria-labelledby="handbookTitle"><button class="handbook-close" data-close aria-label="Close handbook section">×</button><div class="eyebrow">Official Utah Driver Handbook</div><h2 id="handbookTitle">${esc(m.section)}</h2><p>${esc(m.summary)}</p><div class="handbook-rule"><b>For this question</b><br>${esc(q.explanation)}</div><p class="muted">This opens the official handbook at the relevant section. Page locations are a study shortcut—always follow the handbook itself if rules change.</p><a class="btn primary" href="${PDF}#page=${m.page}" target="_blank" rel="noopener">Open official handbook</a></section>`;document.body.appendChild(el);el.querySelector('.handbook-close').focus()}
function close(){let m=document.getElementById('handbookModal');if(m){m.remove();prior?.focus()}}document.addEventListener('click',e=>{let b=e.target.closest('[data-handbook]');if(b)open(b.dataset.handbook);if(e.target.closest('[data-close]'))close()});document.addEventListener('keydown',e=>{let m=document.getElementById('handbookModal');if(!m)return;if(e.key==='Escape'){e.preventDefault();close()}if(e.key==='Tab'){let f=[...m.querySelectorAll('button,a[href]')];if(!f.length)return;let first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});new MutationObserver(add).observe(document.getElementById('app'),{childList:true,subtree:true});document.head.insertAdjacentHTML('beforeend',`<style>.handbook-link{margin:12px 0 0;border:0;background:transparent;color:var(--blue);font-weight:800;cursor:pointer;padding:0}.handbook-modal{position:fixed;inset:0;z-index:10;display:grid;place-items:center;padding:18px}.handbook-backdrop{position:absolute;inset:0;background:#081a2dcc}.handbook-dialog{position:relative;z-index:1;max-width:560px;width:100%;max-height:88vh;overflow:auto;background:#fff;color:#112840;border-radius:20px;padding:25px;box-shadow:0 18px 70px #0005}.handbook-dialog h2{margin:7px 0 12px;font-size:24px}.handbook-close{position:absolute;right:14px;top:12px;border:0;background:#edf2f7;border-radius:10px;font-size:24px;line-height:1;padding:6px 10px;cursor:pointer}.handbook-rule{background:#edf4ff;border-radius:12px;padding:14px;margin:15px 0;line-height:1.5}@media(max-width:500px){.handbook-dialog{padding:21px}.handbook-modal{padding:10px}}</style>`);add()})();
